# Generated by Django 3.2.4 on 2021-06-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safekeep', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
